/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Collection {
  'id' : CollectionId,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
}
export type CollectionId = string;
export interface ContactMessage {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface Product {
  'id' : ProductId,
  'collectionId' : CollectionId,
  'name' : string,
  'tags' : Array<string>,
  'description' : string,
  'colorVariants' : [] | [Array<string>],
  'available' : boolean,
  'sizeVariants' : [] | [Array<string>],
  'imageUrl' : string,
  'price' : string,
}
export type ProductId = string;
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [
      ProductId,
      string,
      string,
      string,
      string,
      boolean,
      Array<string>,
      [] | [Array<string>],
      [] | [Array<string>],
      CollectionId,
    ],
    undefined
  >,
  'createCollection' : ActorMethod<
    [CollectionId, string, string, string],
    undefined
  >,
  'getAllCollections' : ActorMethod<[], Array<Collection>>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCollection' : ActorMethod<[CollectionId], Collection>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getProductsByCollection' : ActorMethod<[CollectionId], Array<Product>>,
  'submitContactMessage' : ActorMethod<
    [string, string, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];