/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Text;
export const CollectionId = IDL.Text;
export const Collection = IDL.Record({
  'id' : CollectionId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const ContactMessage = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'collectionId' : CollectionId,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'colorVariants' : IDL.Opt(IDL.Vec(IDL.Text)),
  'available' : IDL.Bool,
  'sizeVariants' : IDL.Opt(IDL.Vec(IDL.Text)),
  'imageUrl' : IDL.Text,
  'price' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [
        ProductId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Vec(IDL.Text)),
        IDL.Opt(IDL.Vec(IDL.Text)),
        CollectionId,
      ],
      [],
      [],
    ),
  'createCollection' : IDL.Func(
      [CollectionId, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllCollections' : IDL.Func([], [IDL.Vec(Collection)], ['query']),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCollection' : IDL.Func([CollectionId], [Collection], ['query']),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getProductsByCollection' : IDL.Func(
      [CollectionId],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Text;
  const CollectionId = IDL.Text;
  const Collection = IDL.Record({
    'id' : CollectionId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const ContactMessage = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'collectionId' : CollectionId,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'colorVariants' : IDL.Opt(IDL.Vec(IDL.Text)),
    'available' : IDL.Bool,
    'sizeVariants' : IDL.Opt(IDL.Vec(IDL.Text)),
    'imageUrl' : IDL.Text,
    'price' : IDL.Text,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [
          ProductId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Vec(IDL.Text)),
          IDL.Opt(IDL.Vec(IDL.Text)),
          CollectionId,
        ],
        [],
        [],
      ),
    'createCollection' : IDL.Func(
        [CollectionId, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllCollections' : IDL.Func([], [IDL.Vec(Collection)], ['query']),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCollection' : IDL.Func([CollectionId], [Collection], ['query']),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getProductsByCollection' : IDL.Func(
        [CollectionId],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };