/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ContactMessage {
    name: string;
    email: string;
    message: string;
    timestamp: bigint;
}
export type ProductId = string;
export interface Collection {
    id: CollectionId;
    name: string;
    description: string;
    imageUrl: string;
}
export type CollectionId = string;
export interface Product {
    id: ProductId;
    collectionId: CollectionId;
    name: string;
    tags: Array<string>;
    description: string;
    colorVariants?: Array<string>;
    available: boolean;
    sizeVariants?: Array<string>;
    imageUrl: string;
    price: string;
}
export interface backendInterface {
    addProduct(id: ProductId, name: string, desc: string, price: string, image: string, available: boolean, tags: Array<string>, sizes: Array<string> | null, colors: Array<string> | null, collectionId: CollectionId): Promise<void>;
    createCollection(id: CollectionId, name: string, desc: string, image: string): Promise<void>;
    getAllCollections(): Promise<Array<Collection>>;
    getAllContactMessages(): Promise<Array<ContactMessage>>;
    getAllProducts(): Promise<Array<Product>>;
    getCollection(id: CollectionId): Promise<Collection>;
    getProduct(id: ProductId): Promise<Product>;
    getProductsByCollection(collectionId: CollectionId): Promise<Array<Product>>;
    submitContactMessage(name: string, email: string, message: string, timestamp: bigint): Promise<void>;
}
import type { CollectionId as _CollectionId, Product as _Product, ProductId as _ProductId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addProduct(arg0: ProductId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: boolean, arg6: Array<string>, arg7: Array<string> | null, arg8: Array<string> | null, arg9: CollectionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg8), arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg8), arg9);
            return result;
        }
    }
    async createCollection(arg0: CollectionId, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCollection(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCollection(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getAllCollections(): Promise<Array<Collection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCollections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCollections();
            return result;
        }
    }
    async getAllContactMessages(): Promise<Array<ContactMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactMessages();
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCollection(arg0: CollectionId): Promise<Collection> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollection(arg0);
            return result;
        }
    }
    async getProduct(arg0: ProductId): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_Product_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_Product_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByCollection(arg0: CollectionId): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCollection(arg0);
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCollection(arg0);
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContactMessage(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactMessage(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactMessage(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_Product_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    collectionId: _CollectionId;
    name: string;
    tags: Array<string>;
    description: string;
    colorVariants: [] | [Array<string>];
    available: boolean;
    sizeVariants: [] | [Array<string>];
    imageUrl: string;
    price: string;
}): {
    id: ProductId;
    collectionId: CollectionId;
    name: string;
    tags: Array<string>;
    description: string;
    colorVariants?: Array<string>;
    available: boolean;
    sizeVariants?: Array<string>;
    imageUrl: string;
    price: string;
} {
    return {
        id: value.id,
        collectionId: value.collectionId,
        name: value.name,
        tags: value.tags,
        description: value.description,
        colorVariants: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.colorVariants)),
        available: value.available,
        sizeVariants: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.sizeVariants)),
        imageUrl: value.imageUrl,
        price: value.price
    };
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n3(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<string> | null): [] | [Array<string>] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
